"""Initial migration.

Revision ID: 025b78e7c90b
Revises: 
Create Date: 2024-10-17 01:22:28.559936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025b78e7c90b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_time_worked', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pomodoro_count', sa.Integer(), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pomodoro_count')
        batch_op.drop_column('total_time_worked')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
